"""
Security validator for generated code

SECURITY-CRITICAL: This module validates all code generated by the Codex Worker
to ensure it doesn't contain dangerous patterns or security vulnerabilities.

All generated code MUST pass validation before being returned to Claude Code.
"""

import ast
import re
from typing import Any


# Forbidden patterns (from AGENTS.md and CLAUDE.md)
FORBIDDEN_PATTERNS = [
    # Shell command injection
    r"shell\s*=\s*True",
    r"os\.system\s*\(",
    r"commands\.(getoutput|getstatusoutput)\s*\(",

    # Code execution
    r"\beval\s*\(",
    r"\bexec\s*\(",
    r"__import__\s*\(",
    r"compile\s*\(",

    # Path traversal
    r"\.\./",
    r"\.\.\\",

    # Dangerous file operations
    r"rm\s+-rf",
    r"shutil\.rmtree\s*\(",

    # Network operations (not needed for MVP)
    r"urllib\.request",
    r"requests\.(get|post|put|delete)",
    r"curl\s+",
    r"wget\s+",

    # Sudo or privilege escalation
    r"\bsudo\s+",
    r"os\.setuid",
    r"os\.setgid",
]

# Forbidden imports
FORBIDDEN_IMPORTS = {
    "os.system",
    "commands",
    "pty",
    "paramiko",  # SSH library, not needed
    "fabric",    # Remote execution, not needed
}

# Required patterns for specific task types
REQUIRED_PATTERNS = {
    "schema": [
        r"from pydantic import",
        r"class \w+\(BaseModel\):",
    ],
    "tests": [
        r"import pytest|from pytest",
        r"def test_\w+",
    ],
}


def validate_generated_code(
    code: str,
    task_type: str,
    constraints: list[str],
) -> dict[str, Any]:
    """
    Validate generated code for security and quality.

    Args:
        code: Generated code to validate
        task_type: Type of task (schema, tests, template, boilerplate)
        constraints: List of constraints that were specified

    Returns:
        Dictionary with validation result:
        {
            "valid": bool,
            "errors": list[str],
            "warnings": list[str],
            "checks_passed": list[str],
        }
    """
    errors = []
    warnings = []
    checks_passed = []

    # Check 1: Code must not be empty
    if not code or not code.strip():
        errors.append("Generated code is empty")
        return {
            "valid": False,
            "errors": errors,
            "warnings": warnings,
            "checks_passed": checks_passed,
        }
    checks_passed.append("Non-empty code")

    # Check 2: Forbidden patterns
    for pattern in FORBIDDEN_PATTERNS:
        if re.search(pattern, code, re.IGNORECASE):
            errors.append(f"Forbidden pattern detected: {pattern}")

    if not errors:
        checks_passed.append("No forbidden patterns")

    # Check 3: Forbidden imports (Python code only)
    if task_type in ["schema", "tests", "boilerplate"]:
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name in FORBIDDEN_IMPORTS:
                            errors.append(f"Forbidden import: {alias.name}")
                elif isinstance(node, ast.ImportFrom):
                    if node.module and node.module in FORBIDDEN_IMPORTS:
                        errors.append(f"Forbidden import: {node.module}")

            if not any("Forbidden import" in e for e in errors):
                checks_passed.append("No forbidden imports")
        except SyntaxError as e:
            errors.append(f"Syntax error in generated Python code: {str(e)}")

    # Check 4: Required patterns for task type
    if task_type in REQUIRED_PATTERNS:
        for pattern in REQUIRED_PATTERNS[task_type]:
            if not re.search(pattern, code):
                errors.append(f"Missing required pattern for {task_type}: {pattern}")

        if not any("Missing required pattern" in e for e in errors):
            checks_passed.append(f"Required patterns for {task_type} present")

    # Check 5: Subprocess usage validation (if present)
    if "subprocess" in code:
        # subprocess is allowed, but only without shell=True
        if re.search(r"shell\s*=\s*True", code):
            errors.append("subprocess with shell=True is forbidden")
        else:
            warnings.append(
                "subprocess usage detected. Ensure it's used safely without shell=True."
            )
            checks_passed.append("subprocess usage appears safe")

    # Check 6: Constraint validation
    for constraint in constraints:
        constraint_lower = constraint.lower()

        # Check for "no shell=True" constraint
        if "no shell" in constraint_lower and "shell=True" in code:
            errors.append(f"Constraint violation: {constraint}")

        # Check for "type hints" constraint
        if "type hint" in constraint_lower:
            if task_type in ["schema", "tests", "boilerplate"]:
                # Basic check: look for function definitions with annotations
                if re.search(r"def \w+\([^)]*\)\s*:", code):
                    if not re.search(r"def \w+\([^)]*:\s*\w+", code):
                        warnings.append(
                            f"Constraint '{constraint}' may not be fully satisfied. "
                            "Consider reviewing type hints."
                        )
                    else:
                        checks_passed.append("Type hints present")

        # Check for Pydantic version constraint
        if "pydantic v2" in constraint_lower or "pydantic 2" in constraint_lower:
            # Check for v2 patterns
            if "from pydantic import" in code:
                if "ConfigDict" in code or "model_validator" in code or "Field" in code:
                    checks_passed.append("Pydantic v2 syntax detected")
                else:
                    warnings.append(
                        "Pydantic v2 constraint specified but v2-specific patterns not detected"
                    )

    # Check 7: Security-critical files should never be generated
    security_critical_indicators = [
        "safety.py",
        "validator.py",
        "ALLOWED_COMMANDS",
        "command_whitelist",
    ]

    for indicator in security_critical_indicators:
        if indicator in code and task_type != "tests":
            warnings.append(
                f"Generated code contains '{indicator}'. "
                "Security-critical code should be written by Commander, not Worker."
            )

    # Determine validity
    valid = len(errors) == 0

    return {
        "valid": valid,
        "errors": errors,
        "warnings": warnings,
        "checks_passed": checks_passed,
    }


def validate_openfoam_template(template_content: str) -> dict[str, Any]:
    """
    Validate OpenFOAM template configuration.

    Args:
        template_content: OpenFOAM dictionary content

    Returns:
        Validation result dictionary
    """
    errors = []
    warnings = []
    checks_passed = []

    if not template_content.strip():
        errors.append("Template content is empty")
        return {
            "valid": False,
            "errors": errors,
            "warnings": warnings,
            "checks_passed": checks_passed,
        }

    # Check for FoamFile header (recommended but not required)
    if "FoamFile" in template_content:
        checks_passed.append("FoamFile header present")
    else:
        warnings.append("FoamFile header not found. It's recommended for OpenFOAM files.")

    # Check for common OpenFOAM keywords
    openfoam_keywords = [
        "dimensions",
        "internalField",
        "boundaryField",
        "solvers",
        "relaxationFactors",
    ]

    found_keywords = [kw for kw in openfoam_keywords if kw in template_content]
    if found_keywords:
        checks_passed.append(f"OpenFOAM keywords found: {', '.join(found_keywords)}")

    # Basic syntax check: balanced braces
    open_braces = template_content.count("{")
    close_braces = template_content.count("}")

    if open_braces != close_braces:
        errors.append(
            f"Unbalanced braces: {open_braces} opening, {close_braces} closing"
        )
    else:
        checks_passed.append("Balanced braces")

    valid = len(errors) == 0

    return {
        "valid": valid,
        "errors": errors,
        "warnings": warnings,
        "checks_passed": checks_passed,
    }
